[package]
name = "smol"
version = "0.1.10"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "A small and fast async runtime"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stjepang/smol"
homepage = "https://github.com/stjepang/smol"
documentation = "https://docs.rs/smol"
keywords = ["async", "await", "future", "io", "networking"]
categories = ["asynchronous", "concurrency", "network-programming"]
readme = "README.md"
# autoexamples = false

[features]
# Optional feature for seamless integration with crates depending on tokio.
# It creates a global tokio runtime and sets up its context inside smol.
#
# Enable the feature as follows:
# ```
# [dependencies]
# smol = { version = "0.1", features = ["tokio02"] }
# ```
tokio02 = ["tokio"]

[dependencies]
async-task = "3.0.0"
crossbeam-deque = "0.7.3"
crossbeam-queue = "0.2.1"
crossbeam-utils = "0.7.2"
futures-util = { version = "0.3.5", default-features = false, features = ["std", "io"] }
futures-io = { version = "0.3.5", default-features = false, features = ["std"] }
once_cell = "1.3.1"
piper = "0.1.2"
scoped-tls-hkt = "0.1.2"
slab = "0.4.2"
socket2 = { version = "0.3.12", features = ["pair", "unix"] }

[dependencies.tokio]
version = "0.2.19"
default-features = false
features = ["rt-threaded"]
optional = true

[target.'cfg(unix)'.dependencies]
libc = "0.2.70"

[target.'cfg(windows)'.dependencies]
wepoll-binding = "2.0.2"

# [dev-dependencies]

[[bench]]
name = "spawn"
harness = false


## Examples


[target.'cfg(windows)'.dev-dependencies]
uds_windows = "0.1.4"

[target.'cfg(target_os = "linux")'.dev-dependencies]
inotify = { version = "0.8.2", default-features = false }
nix = "0.17.0"
timerfd = "1.1.1"

[dev-dependencies]

anyhow = "1.0.28"
async-h1 = "1.1.2"
async-native-tls = "0.3.3"
async-std = "1.5.0"
async-tungstenite = { version = "0.4.2", features = ["async-native-tls"] }
base64 = "0.12.0"
criterion = "0.3"
ctrlc = "3.1.4"
futures = { version = "0.3.5", default-features = false, features = ["std"] }
# futures = "0.3.4"
http = "0.2.1"
http-types = "1.2.0"
hyper = { version = "0.13.5", default-features = false, features = ["stream"] }
native-tls = "0.2.4"
num_cpus = "1.13.0"
piper = "0.1.1"
reqwest = "0.10.4"
scraper = "0.11.0"
signal-hook = "0.1.13"
smol = { path = ".", features = ["tokio02"] }
surf = { version = "2.0.0-alpha.1", default-features = false, features = ["h1-client"] }
tempfile = "3.1.0"
tokio = { version = "0.2.18", default-features = false }
tungstenite = "0.10.1"
url = "2.1.1"
